lecture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]
# handler404 = 'todo.views.error_404_view'

todo/urls.py
from django.urls import path

from .views import index, detail, create,update,delete,updatetodo,deletetodo,createform,item_create

app_name='todo'
urlpatterns = [
    path('', index, name='index'),
    path('<int:list_id>/', detail, name='list_details'),
    path('createlist/', create, name='list_create'),
    path('update/',update, name='update_list'),
    path('delete/',delete, name='delete_list'),
    path('<int:list_id>/todo/updatetodo/',updatetodo,name="updatetodo"),
    path('<int:list_id>/todo/deletetodo/',deletetodo,name="deletetodo"),
    path('create/',createform,name="createform"),
    path('item_create/',item_create, name='item_create'),


]

todo/models.py
from django.db import models
# Create your models here.

class TodoList(models.Model):

    list_name = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.list_name}"

class TodoItem(models.Model):

    title = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    due_date = models.DateTimeField()
    todo_list = models.ForeignKey(to=TodoList, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.todo_list.list_name}: {self.title} "

todo/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse, Http404,HttpResponseRedirect
from django.template import loader
from .models import TodoList
from .models import TodoItem

# # Create your views here.
# def error_404_view(request,exception):
#     # raise Http404("404 error")
#     return render(request,"todo/404err.html")

def index(request):
    try:
        todolists = TodoList.objects.all()
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    context = {
        'todolists': todolists,
            }
    return render(request, 'todo/index.html', context)

def detail(request, list_id):
    try:
        todolist = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        raise Http404("This List Does not Exists")
    try:
        items_list = TodoItem.objects.filter(todo_list=todolist)
    except TodoList.DoesNotExist:
        raise Http404("This item Does not Exists")
    context = {
        'todolist': todolist,
        'items_list': items_list,
        'list_id':list_id
    }
    return render(request, 'todo/details.html', context)

def create(request):
    if request.method == "GET":
        cont={"error":"",}
        return render(request, 'todo/createlist.html',cont)
    name = request.POST["name"]
    desc = request.POST["title"]
    due_date = str(request.POST["date"])
    print(due_date)
    # due_tim = request.POST["time"]
    if (TodoList.objects.filter(list_name=name).exists()):
        raise Http404("You cant give same tittle")
    else:
        try:
            TodoList.objects.create(list_name=name)
            TodoItem.objects.create(title=desc,due_date=due_date,todo_list=TodoList.objects.get(list_name=name))
        except:
            cont = {"error":"Error in creating list"}
            return render(request, 'todo/createlist.html',cont)
    
    return redirect('/todo/')

def update(request):

    item = request.POST["item"]
    name = request.POST["name"]
    desc = request.POST["title"]
    check = request.POST["check"]
    
    # due_tim = request.POST["time"]
    try:
        todolist = TodoList.objects.get(id=name)
    except:
        raise Http404("Error occoured due to lack of information")
    if(request.POST["date"]):
        due_date = request.POST["date"]
        TodoItem.objects.filter(todo_list=todolist,id=item).update(title=desc,due_date=due_date,checked=check)
    else:
        TodoItem.objects.filter(todo_list=todolist,id=item).update(title=desc,checked=check)
    return redirect('/todo/'+name+'/')

def delete(request):
    id = request.POST["name"]
    name = TodoList.objects.get(id = id)
    try:
        todolist = TodoList.objects.get(list_name=name)
    except:
        raise Http404("Error occoured due to lack of information")
    TodoList.objects.filter(list_name=name).delete()
    lists = TodoList.objects.all()
    context = {
        'todolists': lists,

    }
    return render(request, 'todo/index.html', context)
def updatetodo(request,list_id,item_id):
    try:
        todoitem = item_id
        TodoList.objects.get(id = list_id)
        itemtitle = TodoItem.objects.get(id = todoitem).title
    except:
        raise Http404("Error occoured due to lack of information")
    try:
        todolist = list_id
    except:
        raise Http404("list item not found")    
    context = {
        'todolist':todolist,
        'todoitem':todoitem,
        'itemtitle':itemtitle,
    }
    return render(request, 'todo/update.html', context)

def deletetodo(request,list_id,item_id):
    try:
        id = item_id
        todoitem = TodoItem.objects.get(id = id).title
        todolist = TodoList.objects.get(id = list_id)
    except:
        raise Http404("list item not found") 
    TodoItem.objects.filter(todo_list=todolist,id = id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def createform(request,list_id):
    id = list_id
    name  = TodoList.objects.get(id = id)
    context={
        'todolist' : name
    }
    return render(request, 'todo/create.html', context)

def item_create(request):
    try:
        id = request.POST["name"]
        name = TodoList.objects.get(id = id)
        desc = request.POST["title"]
        due_date = str(request.POST["date"])
    except:
        raise Http404("cant get sufficient information")
    
    try:
        todolist = TodoList.objects.get(list_name=name)
    except:
        raise  Http404("Error occoured due to lack of information")
    # due_tim = request.POST["time"]
    if (TodoItem.objects.filter(todo_list=todolist,title=desc).exists()):
        raise Http404("You cant give same tittle")

    try:
        TodoItem.objects.create(title=desc,due_date=due_date,todo_list=todolist)
    except:
        raise Http404("Error in creating item in list")
    
    return redirect('/todo/'+id+'/')

templates/todo/404err.html
<html>
<head>
</head>
<body>
<h1> 404 error </h1>
<a href = "/todo/">go to home page</a>
</body>

</html>

templates/todo/create.html
<html>
<head>
        <style>
            .h1{
                background-color:lightyellow;
                padding:20px;
                color:green;

            
            }
            .sub{
                background-color:lightblue;
                border-style: solid;
                width:50vw;
                padding : 20px;
                justify-content:centre;
            }
            body{
                background-color:lightyellow;
            }
        </style>

</head>
<body>
{% if error %}
<div class="h1"><span>{{error}}</span></div>
{% endif %}
<div class = "sub">
<form action="/todo/item_create/" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Create New item</h1>
        
        {% comment %} <span name="name" id="name" value = {{todolist}}>{{todolist}}</span> {% endcomment %}
        {% comment %} <input type="text" name="name" id="name" value = {{todolist}}><br> {% endcomment %}
        <span>todo item</span><br>
        <input type="tittle" name="title" id="title" required><br>
        <span>due date of event</span><br>
        <input type="datetime-local" name="date" id="date" placeholder="dd-mm-yyyy" value="" min="1997-01-01" max="2030-12-31" required><br>
        {% comment %} <input type="date" name="date" ><br> {% endcomment %}
        <span>due time of event</span><br>
        {% comment %} <input type="time" name="time" id="time" required><br> {% endcomment %}
        <button name="name" id="name" value = {{todolist.id}} >Add item</button>
    </fieldset>

</form>
</div>
<a href="#" onclick="javascript:window.history.back(-1);return false;"><button>Back</button></a>
</body>
</html>

templates/todo/createlist.html
<html>
<head>
        <style>
            .h1{
                background-color:lightyellow;
                padding:20px;
                color:green;

            
            }
            .sub{
                background-color:lightblue;
                border-style: solid;
                width:50vw;
                padding : 20px;
                justify-content:centre;
            }
            body{
                background-color:lightyellow;
            }
        </style>

</head>
<body>
{% if error %}
<div class="h1"><span>{{error}}</span></div>
{% endif %}
<div class = "sub">
<form action="{% url 'todo:list_create' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>Create New List</h1>
        <span>Listname</span><br>
        <input type="text" name="name" id="name" required><br>
        <span>todo item</span><br>
        <input type="tittle" name="title" id="title" required><br>
        <span>due date of event</span><br>
        <input type="datetime-local" name="date" id="date" required><br>
        {% comment %} <input type="date" name="date" ><br> {% endcomment %}
        <span>due time of event</span><br>
        {% comment %} <input type="time" name="time" id="time" required><br> {% endcomment %}
        <input type="submit">
    </fieldset>

</form>
</div>
<a href="#" onclick="javascript:window.history.back(-1);return false;"><button>Back</button></a>
</body>
</html>

templates/todo/details.html
<!DOCTYPE html> 
<html>
    <head>
        <style>
            .check{
                width:50px;
                height:50px;
                
            }
            .h1{
               
                padding:20px;
                color:green;

            
            }
            .sub{

                display:flex;
                flex-wrap:wrap;
                
                width:70vw;
                
                justify-content:centre;
            }
          
            li{
                text-decoration : none;
                background-color:white;
                width:70vw;
            }
            ul{
                list-decoration:none;
                padding-inline-start: 0px;
            }
            .one{
                width:25vw;
                height:50px;
                border-style: solid;
                justify-content:centre;
                padding-left:20px;


            }
            .two{
                width:15vw;
                overflow-y:hidden;
                height:50px;
                border-style: solid;
                justify-content:centre;
                margin-left:10px;

            }
            .three{
                width:10vw;
                height:50px;
                border-style: solid;
                justify-content:centre;
                 margin-left:10px;
            }
            .but>a>button{
                margin-left:10px;
                height : 50px;
                height:50px;
                
            }
            button{
                height:50px;
                margin-left:10px;
            }
      
        </style>

    </head>
    <body>
        <a href='create/'<button value ={{todolist.id}} id = "todo"name = "todo">Add Item</button></a>
         {% comment %} <a href = "/todo/create"><button>Add</button></a> {% endcomment %}

        <div class="h1"><h1>{{todolist.list_name}}</h1></div>
            <ul>
                
                {% for item in items_list %}
               
                <li> <div class = "sub"><div class = "one"><h2>{{item.title}}</h2></div>
                <div class = "two"><h2>{{item.due_date}}</h2></div>
                {% comment %} <div class = "three"><h2>{{item.due_tim}}</h2></div> {% endcomment %}
                {% if item.checked%}
                <input class = "check" type = "checkbox" checked = True>
                {% else %}
                <input class = "check"type = "checkbox" >
                {% endif %}

                <div class="but"><a href = "{{item.id}}/update/" ><button name="upd" value = {{item.id}}>update</button></a></div><div class="but"><a href = "{{item.id}}/deletetodo/" ><button value= {{item.id}} name = 'title'>delete</button></a></div></div>
                
                </li>
                
             </ul>

         {% comment %} <div class="h1"><h1> You can update your Todo here </h1></div>
                <div class = "sub">
                <form method=post action="/todo/update/">
                {% csrf_token %}
                <input type="date" id="date" name="date"  value=""><br><br>
                <input type="text" id="title" name="title" value={{item.title}}><br><br>
                <input type="time" id="time" name="time" value={{item.due_tim}}><br><br>
                <button id = "name" name = "name" value = {{todolist.list_name}}>submit</button>
                </form>
                </div> {% endcomment %}
                {% comment %} <li><h2>{{item.title}}</h2></li>
                <li><h2>{{item.due_date}}</h2></li>
                <li><h2>{{item.due_tim}}</h2></li>
                
                <li><h2>Done <input type = "checkbox" value = {{item.checked}}></h2></li> {% endcomment %}

                
                
                {% endfor %}
            <a href = "/todo/">back</a>
            {% comment %} <a href="#" onclick="javascript:window.history.back(-1);return false;"><button>Back</button></a> {% endcomment %}

    </body>
</html>

templates/todo/index.html
<html>
<head>
<style>
body{
    background-color:lightyellow;
}
.flex{
    display: flex;
    background-color:lightblue;
    width : 50vw;
    margin :10px;
    justify-content:space-between;
}
.flex1{
    
    margin: 10px;
  padding: 20px;
  font-size: 30px
}
.flex2{
    margin: 10px;
  padding: 20px;
  font-size: 30px
}
</style>
</head>
<body>
<a href = "/todo/createlist"><button>Add</button></a>
{% if todolists %}


    <ul>
        {% for todolist in todolists %}
        <form method = "post" action ="/todo/delete/">
        {% csrf_token %}
        <div class = "flex">
        <div class = "flex1">
        <li><a href="/todo/{{todolist.id}}">{{todolist.list_name}}</a></li>
        </div>
        <div class = "flex2" >
        <button value={{todolist.id}} name="name">Delete</button>
        </div>
        </div>
        </form>

        {% endfor %}
    </ul>

{% endif %}
</body>
</html>

templates/todo/update.html
                <div class="h1"><h1> You can update your Todo here </h1></div>
                <div class = "sub">
                <form method=post action="/todo/update/">
                {% csrf_token %}
                <input type = "hidden" id="item" name = "item" value={{todoitem}}>
                <input type="datetime-local" id="date" name="date"  value=""><br><br>
                <input type="text" id="title" name="title" value={{itemtitle}}><br><br>
                {% comment %} <input type="time" id="time" name="time" value=""><br><br> {% endcomment %}
                <span> mark </span>
                <input type = 'radio'  value=True name ="check" required>
                <span> unmark </span>
                <input type = 'radio'  value=False name="check" required><br>
                <button id = "name" name = "name" value = {{todolist}}>submit</button>
                </form>
                </div>